In [13]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva","Ravi","Suchitra"],
    "Age": [25, 30, 35, 40, 45,24,35],
    "Department": ["HR", "Finance", "IT", "Marketing", "Finance","HR","IT"],
    "Salary": [50000, 60000, 75000, 80000, 65000,45000,60000]
}

df = pd.DataFrame(data)
df

       Name  Age Department  Salary
0     Alice   25         HR   50000
1       Bob   30    Finance   60000
2   Charlie   35         IT   75000
3     David   40  Marketing   80000
4       Eva   45    Finance   65000
5      Ravi   24         HR   45000
6  Suchitra   35         IT   60000

In [4]:
df.head()

      Name  Age Department  Salary
0    Alice   25         HR   50000
1      Bob   30    Finance   60000
2  Charlie   35         IT   75000
3    David   40  Marketing   80000
4      Eva   45    Finance   65000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      object
 1   Age         5 non-null      int64
 2   Department  5 non-null      object
 3   Salary      5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 288.0+ bytes

In [6]:
df.describe()

             Age        Salary
count   5.000000      5.000000
mean   35.000000  66000.000000
std     7.905694  11937.336386
min    25.000000  50000.000000
25%    30.000000  60000.000000
50%    35.000000  65000.000000
75%    40.000000  75000.000000
max    45.000000  80000.000000

In [7]:
df["Name"]              # single column
df[["Name","Salary"]]   # multiple columns

      Name  Salary
0    Alice   50000
1      Bob   60000
2  Charlie   75000
3    David   80000
4      Eva   65000

In [8]:
df[df["Age"] > 30]        # people older than 30

      Name  Age Department  Salary
2  Charlie   35         IT   75000
3    David   40  Marketing   80000
4      Eva   45    Finance   65000

In [9]:
df[df["Department"] == "Finance"]   # Finance staff

  Name  Age Department  Salary
1  Bob   30    Finance   60000
4  Eva   45    Finance   65000

In [10]:
df.sort_values("Salary", ascending=False)

      Name  Age Department  Salary
3    David   40  Marketing   80000
2  Charlie   35         IT   75000
4      Eva   45    Finance   65000
1      Bob   30    Finance   60000
0    Alice   25         HR   50000

In [19]:
df.groupby("Department")["Salary"].median()

Department
Finance      62500.0
HR           47500.0
IT           67500.0
Marketing    80000.0
Name: Salary, dtype: float64