In [1]:
import sys
sys.executable, sys.version

('c:\\Software\\anaconda3\\envs\\dbt-demo\\python.exe',
 '3.11.14 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 18:30:03) [MSC v.1929 64 bit (AMD64)]')

In [3]:
import duckdb
duckdb.sql("select 1 as ok").df()

   ok
0   1

In [4]:
import duckdb
import pandas as pd

DB_PATH = r"C:\kworld\AI_World\CDO-Innovation-Hub\Data-Engineering\dbt-analytics-lakehouse-demo\warehouse\dev.duckdb"
con = duckdb.connect(DB_PATH)

In [5]:
con.execute("""
SELECT table_schema, table_name
FROM information_schema.tables
WHERE table_schema NOT IN ('information_schema')
ORDER BY 1,2
""").df()

  table_schema              table_name
0         main           dim_customers
1         main              fct_orders
2         main  fct_orders__dbt_backup
3         main           raw_customers
4         main              raw_orders
5         main           stg_customers
6         main              stg_orders

In [8]:
## check staging tables
con.execute("SELECT * FROM stg_customers LIMIT 10").df()

   customer_id customer_name     segment
0            1         Alice    Consumer
1            2           Bob         SMB
2            3       Charlie  Enterprise
3            4         Deepa    Consumer
4            5         Ethan         SMB

In [9]:
## check staging tables
con.execute("SELECT * FROM stg_orders LIMIT 10").df()

   order_id  customer_id order_date  amount
0      1001            1 2025-01-05   120.5
1      1002            1 2025-01-10    60.0
2      1003            2 2025-01-15   300.0
3      1004            3 2025-02-01   800.0
4      1005            4 2025-02-10    25.0
5      1006            5 2025-02-12   150.0
6      1007            2 2025-02-20    75.0
7      1008            3 2025-03-01    60.0
8      1009            1 2025-03-05   220.0
9      1010            4 2025-03-08    45.0

In [6]:
con.execute("SELECT * FROM dim_customers LIMIT 10").df()

   customer_id customer_name     segment  order_count  lifetime_value
0            1         Alice    Consumer            3           400.5
1            2           Bob         SMB            2           375.0
2            3       Charlie  Enterprise            2           860.0
3            4         Deepa    Consumer            2            70.0
4            5         Ethan         SMB            1           150.0

In [10]:
con.execute("SELECT * FROM fct_orders ORDER BY order_date DESC LIMIT 10").df()

   order_id  customer_id order_date  amount
0      1010            4 2025-03-08    45.0
1      1009            1 2025-03-05   220.0
2      1008            3 2025-03-01    60.0
3      1007            2 2025-02-20    75.0
4      1006            5 2025-02-12   150.0
5      1005            4 2025-02-10    25.0
6      1004            3 2025-02-01   800.0
7      1003            2 2025-01-15   300.0
8      1002            1 2025-01-10    60.0
9      1001            1 2025-01-05   120.5

In [11]:
con.execute("SELECT count(*) AS orders FROM fct_orders").df()

   orders
0      10

In [12]:
con.execute("""
SELECT customer_id, lifetime_value
FROM dim_customers
ORDER BY lifetime_value DESC
""").df()

   customer_id  lifetime_value
0            3           860.0
1            1           400.5
2            2           375.0
3            5           150.0
4            4            70.0

In [ ]:
# Testing Empemeral views. These don't exist in the database, but should be created when we run the dbt models.

con.execute("""
SELECT *
FROM information_schema.tables
WHERE table_name = 'int_customer_order_metrics'
""").df()

Empty DataFrame
Columns: [table_catalog, table_schema, table_name, table_type, self_referencing_column_name, reference_generation, user_defined_type_catalog, user_defined_type_schema, user_defined_type_name, is_insertable_into, is_typed, commit_action, TABLE_COMMENT]
Index: []